<?php
/**
 * Code generated by permission-contract/codegen-php.mjs DO NOT EDIT.
 *
 * Source: permission-contract v1.11.0
 * Generated at: 2026-08-14
 * Regenerate via: node scripts/codegen-php.mjs permissions.json <out-dir>
 *
 * Permission — closed enum of every permission string in the platform.
 * PHP 8.1 backed enums give compile-time typo protection: a perm not
 * listed here fails the type checker.
 *
 * Permission naming convention: {service}:{resource}:{action}.
 *   service  — one of: athens, mercury, muse, helios, zeta, prometheus
 *   resource — domain noun (project, users, posts, members, ...)
 *   action   — verb (view, write, delete, manage, ...)
 */

declare(strict_types=1);

namespace Wazobia\HeliosPermissions;

enum Permission: string
{
    case AthensProjectDelete = 'athens:project:delete';
    case AthensProjectUpdate = 'athens:project:update';
    case AthensProjectView = 'athens:project:view';
    case AthensServicesDisable = 'athens:services:disable';
    case AthensServicesEnable = 'athens:services:enable';
    case AthensTeamInvite = 'athens:team:invite';
    case AthensTeamRemove = 'athens:team:remove';
    case HeliosExternalRegister = 'helios:external:register';
    case HeliosExternalRevoke = 'helios:external:revoke';
    case HeliosExternalView = 'helios:external:view';
    case HeliosInvitationsCreate = 'helios:invitations:create';
    case HeliosInvitationsRevoke = 'helios:invitations:revoke';
    case HeliosMembersInvite = 'helios:members:invite';
    case HeliosMembersRemove = 'helios:members:remove';
    case HeliosMembersView = 'helios:members:view';
    case HeliosRolesAssign = 'helios:roles:assign';
    case HeliosRolesRevoke = 'helios:roles:revoke';
    case HeliosTenantSwitchSelf = 'helios:tenant:switch:self';
    case HeliosTenantTransfer = 'helios:tenant:transfer';
    case MercuryApiKeysCreate = 'mercury:api_keys:create';
    case MercuryApiKeysManage = 'mercury:api_keys:manage';
    case MercuryApiKeysRead = 'mercury:api_keys:read';
    case MercuryApiKeysRevoke = 'mercury:api_keys:revoke';
    case MercuryAuthConfigAppleCreate = 'mercury:auth_config_apple:create';
    case MercuryAuthConfigAppleUpdate = 'mercury:auth_config_apple:update';
    case MercuryAuthConfigForgotPasswordCreate = 'mercury:auth_config_forgot_password:create';
    case MercuryAuthConfigForgotPasswordRead = 'mercury:auth_config_forgot_password:read';
    case MercuryAuthConfigForgotPasswordUpdate = 'mercury:auth_config_forgot_password:update';
    case MercuryAuthConfigOauthCreate = 'mercury:auth_config_oauth:create';
    case MercuryAuthConfigOauthUpdate = 'mercury:auth_config_oauth:update';
    case MercuryAuthConfigRead = 'mercury:auth_config:read';
    case MercuryConnectionGoogleRevokeSelf = 'mercury:connection_google:revoke:self';
    case MercuryConnectionImapCreateSelf = 'mercury:connection_imap:create:self';
    case MercuryConnectionImapRevokeSelf = 'mercury:connection_imap:revoke:self';
    case MercuryConnectionOauthCompleteSelf = 'mercury:connection_oauth:complete:self';
    case MercuryConnectionOauthInitiateSelf = 'mercury:connection_oauth:initiate:self';
    case MercuryConnectionOauthRefresh = 'mercury:connection_oauth:refresh';
    case MercuryConnectionSlackPhraseCreateSelf = 'mercury:connection_slack:phrase_create:self';
    case MercuryConnectionSlackRevokeSelf = 'mercury:connection_slack:revoke:self';
    case MercuryConnectionReadSelf = 'mercury:connection:read:self';
    case MercuryEventsConsume = 'mercury:events:consume';
    case MercuryServiceClientsRead = 'mercury:service_clients:read';
    case MercuryUserDeleteSelf = 'mercury:user:delete:self';
    case MercuryUserReadSelf = 'mercury:user:read:self';
    case MercuryUserWriteSelf = 'mercury:user:write:self';
    case MercuryUsersBatchRead = 'mercury:users:batch_read';
    case MercuryUsersRead = 'mercury:users:read';
    case MercuryUsersWrite = 'mercury:users:write';
    case MuseAuthorCreate = 'muse:author:create';
    case MuseAuthorDelete = 'muse:author:delete';
    case MuseAuthorRead = 'muse:author:read';
    case MuseAuthorUpdate = 'muse:author:update';
    case MuseBlogCreate = 'muse:blog:create';
    case MuseBlogDelete = 'muse:blog:delete';
    case MuseBlogRead = 'muse:blog:read';
    case MuseBlogUpdate = 'muse:blog:update';
    case MuseCategoryCreate = 'muse:category:create';
    case MuseCategoryDelete = 'muse:category:delete';
    case MuseCategoryRead = 'muse:category:read';
    case MuseCategoryUpdate = 'muse:category:update';
    case MuseDraftsRead = 'muse:drafts:read';
    case MuseDraftsWrite = 'muse:drafts:write';
    case MuseFaqCreate = 'muse:faq:create';
    case MuseFaqDelete = 'muse:faq:delete';
    case MuseFaqUpdate = 'muse:faq:update';
    case MusePostsDelete = 'muse:posts:delete';
    case MusePostsRead = 'muse:posts:read';
    case MusePostsRevert = 'muse:posts:revert';
    case MusePostsWrite = 'muse:posts:write';
    case MuseRedirectAnalytics = 'muse:redirect:analytics';
    case MuseRedirectCreate = 'muse:redirect:create';
    case MuseRedirectDelete = 'muse:redirect:delete';
    case MuseRedirectRead = 'muse:redirect:read';
    case MuseRedirectUpdate = 'muse:redirect:update';
    case MuseTagCreate = 'muse:tag:create';
    case MuseTagDelete = 'muse:tag:delete';
    case MuseTagRead = 'muse:tag:read';
    case MuseTagUpdate = 'muse:tag:update';
    case PrometheusFormsCreate = 'prometheus:forms:create';
    case PrometheusFormsDelete = 'prometheus:forms:delete';
    case PrometheusFormsRead = 'prometheus:forms:read';
    case PrometheusFormsUpdate = 'prometheus:forms:update';
    case PrometheusResponsesAnalytics = 'prometheus:responses:analytics';
    case PrometheusResponsesDelete = 'prometheus:responses:delete';
    case PrometheusResponsesRead = 'prometheus:responses:read';
    case PrometheusResponsesUpdate = 'prometheus:responses:update';
    case ZetaBillingManage = 'zeta:billing:manage';
    case ZetaBillingView = 'zeta:billing:view';
    case ZetaDriversManage = 'zeta:drivers:manage';
    case ZetaDriversView = 'zeta:drivers:view';
    case ZetaFinesAssign = 'zeta:fines:assign';
    case ZetaFinesChallenge = 'zeta:fines:challenge';
    case ZetaFinesCreate = 'zeta:fines:create';
    case ZetaFinesPay = 'zeta:fines:pay';
    case ZetaFinesView = 'zeta:fines:view';
    case ZetaFleetEdit = 'zeta:fleet:edit';
    case ZetaFleetView = 'zeta:fleet:view';
    case ZetaReportsView = 'zeta:reports:view';
    case ZetaTeamManage = 'zeta:team:manage';
    case ZetaTenantConfigure = 'zeta:tenant:configure';
}
